### ISSUE TITLE
Check validity of user input

### ISSUE THREAD

**Issue by bronhuston** [UCSB-CS56-Projects/cs56-math-conversion-quiz#13]
Currently, if the user enters nothing at all, or enters gibberish, the quiz simply treats it as a wrong answer. Change how the input is handled so that if input is not entered in the correct form, the user is informed of the incorrect input and is prompted for a new answer.

~estimated 200

**Comment by jmangel** [comment]
F16 OK (150 pts)

**Comment by jmangel** [comment]
Closed in pull request #42
