### ISSUE TITLE
Fix the build.xml file

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-math-conversion-quiz#18]
the readme insists that it should be able to run a GUI. The Build.xml does not support this.

Fix it 
estimated ~100 points

**Comment by steventedsen** [comment]
the readme just gives the wrong command, it says "ant runGUI", but the build.xml says "ant runGui".

**Comment by PazZaitGivon** [comment]
Good for finding the (incorrectly estimated) bug! If you fix it (ie fix the readme) I would re-estimate this around 25 points

**Comment by steventedsen** [comment]
I sent in a pull request with this issue fixed

**Comment by PazZaitGivon** [comment]
good!
