### ISSUE TITLE
Make the quiz repeatable from the commandline

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-math-conversion-quiz#19]
the quiz ends now and it doesnt allow you to try again. Perhaps allow  an exact repeat option where it regenerates exactly on the same parameters and shows the user how much they improved since the last run once completed

estimated ~ 200points

**Comment by steventedsen** [comment]
I sent in a pull request with this issue fixed

**Comment by PazZaitGivon** [comment]
good!
