### ISSUE TITLE
Make exit explicit

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-math-conversion-quiz#20]
allow people to input new parameters directly by default before (and rerun with those parameters) exiting and make them explicitly choose to exit the program

Estimated ~300points

**Comment by steventedsen** [comment]
I have it ask if they would like to play the game again, and if they choose yes then they are prompted to enter new parameters. if they say no the program is terminated. Does this work?

**Comment by steventedsen** [comment]
I sent in a pull request with this issue fixed

**Comment by PazZaitGivon** [comment]
good
