### ISSUE TITLE
Add "Easy" and "Hard" levels to the GUI

### ISSUE THREAD

**Issue by steventedsen** [UCSB-CS56-Projects/cs56-math-conversion-quiz#23]
allow the user to pick from the regular GUI or one of the new Versions (hard or easy).  The Easy version should give you a second chance if the first answer you input was incorrect, therefore making it an easier game. The hard version should NOT allow any hints while playing the GUI

**Comment by PazZaitGivon** [comment]
~150 for implementing Easy
~150 for implementing Hard
~10 for adding each option into the GUI

These should be sepperate issues...

**Comment by steventedsen** [comment]
ok should I separate them? or leave it how it is for now?

**Comment by PazZaitGivon** [comment]
Please sepperate them actually

**Comment by PazZaitGivon** [comment]
this is ok this time since they are very related but be careful in the future
