### ISSUE TITLE
Add a "Setup Window" for the GUI

### ISSUE THREAD

**Issue by steventedsen** [UCSB-CS56-Projects/cs56-math-conversion-quiz#25]
This should be a window that will pop up before the GUI pops up.  This window should allow to change the parameters of the GUI game and should contain the following parameter questions:
1. How many questions would you like? (1-20 can be used as input, rather than only having the default 10 question test)
2. What Difficulty level? (Regular, Easy, Hard)

After those are implemented there should be a "Select" and "Cancel" button. If "Select" is pushed, then it will create the GUI window using those parameters, and if "Cancel" is selected then it will exit the program.

**Comment by PazZaitGivon** [comment]
This  contains too many sub issues

**Comment by steventedsen** [comment]
ok would you like me to separate it into a couple more?

**Comment by PazZaitGivon** [comment]
Yes, please do so, and link to issues that would be "prerequisites" in them such having an easy or hard level
