### ISSUE TITLE
Make Opening Menu for the Gui

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-math-conversion-quiz#26]
This should be a window that will pop up before the GUI pops up. This window should welcome the user and have a "Start" and "Cancel" button. If "Start" is pushed, then it will create the GUI window, and if "Cancel" is selected then it will exit the program.

~estimated 120

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
Closed in pull request #42
