### ISSUE TITLE
Add Choosing Number of Questions to Opening Menu for Gui

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-math-conversion-quiz#27]
This opening menu window should allow the user to change the parameters of the GUI game and should contain the following parameter question:

How many questions would you like? (1-20 can be used as input, rather than only having the default 10 question test)

~estimated 150

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
Closed with #44
