### ISSUE TITLE
Add "Easy" Option to Opening Menu for Gui

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-math-conversion-quiz#28]
The opening menu window should allow the user to change the parameters of the GUI game and should contain the following parameter question:

What Difficulty level? (Regular, Easy)

Where the Easy version should give you a second chance if the first answer you input was incorrect, therefore making it an easier game. 

~estimated 175

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
Closed with #44
