### ISSUE TITLE
Add "Hard" Option to Opening Menu for Gui

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-math-conversion-quiz#29]
The opening menu window should allow the user to change the parameters of the GUI game and should contain the following parameter question:

What Difficulty level? (Regular, Easy. and Hard)

The hard version should NOT allow any hints while playing the GUI

~estimated 175

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
Closed with #44
