### ISSUE TITLE
Improve Command Line Version

### ISSUE THREAD

**Issue by phillip-fry** [UCSB-CS56-Projects/cs56-math-conversion-quiz#32]
Have the command line version ask the user how many questions they would like in each topic of conversions questions.

**Comment by jmangel** [comment]
F16 OK (50 pts)

**Comment by jmangel** [comment]
Alternatively, allow user to choose mode (ex. octal, binary, etc. or 'mixed')

**Comment by jmangel** [comment]
Closed in pull request #42
