### ISSUE TITLE
Welcome message still appears at the top of the results window 

### ISSUE THREAD

**Issue by robertonares** [UCSB-CS56-Projects/cs56-math-conversion-quiz#55]
The welcome title message still displays on top of the results screen after the quiz has ended. 

![screenshot from 2017-11-15 17-30-09](https://user-images.githubusercontent.com/32424486/32869226-ae542eb4-ca2a-11e7-8203-e70619ed2b87.png)

**Comment by aryamandas** [comment]
F17 OK (50 points)
