### ISSUE TITLE
Fix conversion mode recommendation  

### ISSUE THREAD

**Issue by robertonares** [UCSB-CS56-Projects/cs56-math-conversion-quiz#56]
After a quiz has ended, if the user had a low score on more than one conversion modes the game only recommends the first mode listed on the results page. In this example, the user did equally bad on binary, octal, and decimal modes but only binary was listed at the bottom since it was listed first. 

![screenshot from 2017-11-15 17-38-20](https://user-images.githubusercontent.com/32424486/32869437-ca485fd6-ca2b-11e7-9ca2-b5767fbb2430.png)

**Comment by aryamandas** [comment]
F17 OK (50 points)
