### ISSUE TITLE
Fix conversion mode button feature 

### ISSUE THREAD

**Issue by robertonares** [UCSB-CS56-Projects/cs56-math-conversion-quiz#58]
On the results page, the conversion modes recommended on previous quizzes are still present at the end of a new quiz. This leads to the same mode being recommended multiple times. 

![screenshot from 2017-11-15 17-48-30](https://user-images.githubusercontent.com/32424486/32869688-34964c62-ca2d-11e7-9eae-82ee74905963.png)

**Comment by aryamandas** [comment]
F17 OK (50 points)
