### ISSUE TITLE
Last answer on quiz

### ISSUE THREAD

**Issue by robertonares** [UCSB-CS56-Projects/cs56-math-conversion-quiz#59]
Make it so the result of the last question in the quiz, whether wrong or right, is displayed before reaching the results page. Otherwise, the answer to the last question is displayed at the top of the results window and doesn't really feel like it is supposed to be there. As a user it just looks like a programming mistake and doesn't fit the rest of the content on the results window.

**Comment by aryamandas** [comment]
F17 OK (50 points)
