### ISSUE TITLE
Missing modes on new quiz

### ISSUE THREAD

**Issue by robertonares** [UCSB-CS56-Projects/cs56-math-conversion-quiz#61]
When a mode recommendation button is pressed, the ability to change modes mid-quiz is gone when the new quiz starts.

![issue](https://user-images.githubusercontent.com/32424486/33224486-ac93eca4-d11e-11e7-87a3-2690b77a19bf.JPG)

**Comment by aryamandas** [comment]
F17 OK (25 points)
